localServer:
  domain: s11
  ipAddress: 192.168.68.22
  port: 5555

groupServers:
  - ipAddress: 192.168.78.22
    port: 5555
    domain: s1
  - ipAddress: 192.168.88.22 
    port: 5555
    domain: s2